### PR TITLE
Checkbox Render Logic Fix

### PR DESCRIPTION
**Pull request by Breanna-Stryker**
# Description

Modified the checkbox logic to check for a boolean, if true will add checked=checked to the checkbox.  
Additionally this sets the value of the checkbox to true, to be read in during parsing. 

Correct setup still includes setting any boolean values in .orig.tfvars.json files to false.   Current parser logic would not be able to see a missing value (checkbox values are simply not included in the post/get request.

## Issue reference

The issue this PR will close: #213 

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles or validates correctly
* [X] BASH scripts have been validated using `shellcheck`
* [X] All tests pass (manual and automated)
* [X] The documentation is updated to cover any new or changed features
* [X] Markdown files have been linted using the recommended linter. (See `.vscode/extensions.json`.)
* [X] Relevant issues are linked to this PR

### CODE REVIEW

**Comment by glennmusa** [comment]
Does the trick 👍

**Review by glennmusa — APPROVED** [review]

**Review by brooke-hamilton — APPROVED** [review]
Just confirming: there are currently no checkboxes in the UI that default to checked, correct?
The code deploys the UI and checkboxes appear to function normally.

**Comment by Breanna-Stryker** [comment]
> Just confirming: there are currently no checkboxes in the UI that default to checked, correct?
> The code deploys the UI and checkboxes appear to function normally.

Yes that's correct.  For testing I flipped them to ensure it worked, and then flipped them back.

**Comment by glennmusa** [comment]
> Just confirming: there are currently no checkboxes in the UI that default to checked, correct?
> The code deploys the UI and checkboxes appear to function normally.

The `create_bastion_jumpbox` value defaults to `true`: https://github.com/Azure/missionlz/blob/main/src/core/saca-hub/saca-hub.front.json#L153-L159

**Comment by brooke-hamilton** [comment]
> > Just confirming: there are currently no checkboxes in the UI that default to checked, correct?
> > The code deploys the UI and checkboxes appear to function normally.
> 
> The `create_bastion_jumpbox` value defaults to `true`: https://github.com/Azure/missionlz/blob/main/src/core/saca-hub/saca-hub.front.json#L153-L159 -- but, you'd have had to merged latest into this branch to see that value

Confirmed, I do see it now that it's merged to main. Thank you!

**Pull request merged**
