### PR TITLE
Update mlz.json

### PR DESCRIPTION
**Pull request by kyle-hoyer**
New export of JSON. Fixing template deployment errors.

# Description

_Please explain the changes you've made_

## Issue reference

The issue this PR will close: #766 

## Checklist

Please make sure you've completed the relevant tasks for this PR out of the following list:

* [x] All acceptance criteria in the backlog item are met
* [x] The documentation is updated to cover any new or changed features
* [x] Manual tests have passed
* [x] Relevant issues are linked to this PR

### CODE REVIEW

**Comment by lisamurphy-msft** [comment]
Although the current implementation works with the bicep provided instructions: https://github.com/Azure/missionlz/blob/main/docs/policies.md 
There is a noted issue with the current mlz.json not working with the portal custom template deployment method. 
Testing and the proposed solution works, generating a bug report to link the PR to.

**Review by lisamurphy-msft — APPROVED** [review]

**Review by mikedzikowski — APPROVED** [review]

**Pull request merged**
