### PR TITLE
Modify NSG in hub Resource Group #443

### PR DESCRIPTION
**Pull request by vidyambala**
# Description

_Please explain the changes you've made_
Removed the default NSG rules.

## Issue reference

The issue this PR will close: #[443]

## Checklist

Please make sure you've completed the relevant tasks for this PR out of the following list:

* [x ] All acceptance criteria in the backlog item are met
* [xx ] The documentation is updated to cover any new or changed features
* [ x] Manual tests have passed
* [x ] Relevant issues are linked to this PR

### CODE REVIEW

**Comment by vidyambala** [comment]
Please ignore json template as i accidently pushed it to repo:(

**Review by glennmusa — CHANGES_REQUESTED** [review]
Looks like you need to merge the latest from `main` into your branch, then rebuild your `mlz.json` with `az bicep build -f mlz.bicep`

**Comment by glennmusa** [comment]
You can manually link the Issue to this PR, or, if you update the PR description's [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to remove the square brackets it will close on your behalf when this PR is merged and closed.

**Comment by vidyambala** [comment]
new one replaced this one.

**Pull request closed without merging**
