### PR TITLE
use Bicep loop syntax to create spoke resources the same way

### PR DESCRIPTION
**Pull request by glennmusa**
# Description

This change creates spokes and their dependencies in the same way to reduce the likelihood of introducing changes that causes spokes to differ.

First, it creates a `mlz.bicep` array called `spokes` that is composed of user-defined and defaulted parameters:

https://github.com/Azure/missionlz/blob/d95dc7a43a32260fe6532fab1b313c2f7cff764e/src/bicep/mlz.bicep#L557-L561

Then, it uses [Bicep's loop syntax](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/loops) to create modules for those items in the `spokes` array:

https://github.com/Azure/missionlz/blob/d95dc7a43a32260fe6532fab1b313c2f7cff764e/src/bicep/mlz.bicep#L17-L25

This change also adds documentation on how to retrieve deployed resources programmatically:

https://github.com/Azure/missionlz/blob/d95dc7a43a32260fe6532fab1b313c2f7cff764e/src/bicep/README.md#reference-deployment-output

## Issue reference

The issue this PR will close: #493

## Checklist

Please make sure you've completed the relevant tasks for this PR out of the following list:

* [x] All acceptance criteria in the backlog item are met
* [x] The documentation is updated to cover any new or changed features
* [x] Manual tests have passed
* [x] Relevant issues are linked to this PR

### CODE REVIEW

**Comment by jjansen23** [comment]
Using code space, I deployed this branch but it had a failed deployment ""The resource operation completed with terminal provisioning state 'Failed'" - Not sure if it was as a result of the loop changes or not. It may have been a different issue. The reference is at https://portal.azure.com/#@azureglobal2.onmicrosoft.com/resource/subscriptions/2b01c398-5868-496e-a84f-503ea9eac23a/subdeployments

**Comment by glennmusa** [comment]
> Upon further review, it's a the privateEndpoints that had a conflict. plmlz-gukfcpjuyo Microsoft.Network/privateEndpoints Conflict

Judging by the error message on the `Microsoft.Network/privateEndpoints` "plmlz-gukfcpjuyo" deployment, it smells like a transient error with the service:

```json
{
    "status": "Failed",
    "error": {
        "code": "InternalServerError",
        "message": "An error occurred.",
        "details": []
    }
}
```

Does this occur every time you try to deploy? I have yet to encounter this error, but would love to nail down a root cause if it happens to you repeatedly.

**Comment by jjansen23** [comment]
When I did a redeploy, from the portal, I received a different error : ""A virtual network cannot be linked to multiple zones with overlapping namespaces. You tried to link virtual network with 'privatelink.monitor.azure.com' and 'privatelink.monitor.azure.com' zones."" ... I will start a fresh deploy and advise of the deployment status.

**Comment by jjansen23** [comment]
Deployed successfully.

**Review by jjansen23 — APPROVED** [review]

**Pull request merged**
