### PR TITLE
Update defender.bicep with current securitypricing resource types

### PR DESCRIPTION
**Pull request by LManning-Dev**
Deploy MLZ with deployDefender=$true

Used Get-AzSecurityPricing to get the latest offerings

Expected behavior
All Defender Resources are set to Standard (Status should be On)

Actual behavior
New Resource Types are missed

# Description

_Please explain the changes you've made_

## Issue reference

The issue this PR will close: #720 

## Checklist

Please make sure you've completed the relevant tasks for this PR out of the following list:

* [x] All acceptance criteria in the backlog item are met
* [x] The documentation is updated to cover any new or changed features
* [x] Manual tests have passed
* [x] Relevant issues are linked to this PR

### CODE REVIEW

**Comment by LManning-Dev** [comment]
https://github.com/Azure/missionlz/issues/720

Not sure I had a choice to associate it with the bug.

Thank you

**Comment by lisamurphy-msft** [comment]
Thank you for updating the pricings data for AzureCloud and AzureUSGovernment environments. The last time it was updated these additional offerings were not available in Microsoft Defender for Cloud.

**Review by lisamurphy-msft — APPROVED** [review]

**Pull request merged**
