### PR TITLE
Aks bicep module

### PR DESCRIPTION
**Pull request by renato-marciano**
# Description

Added AKS bicep module. 
Added a ReadMe with example of deploying AKS to Tier 3.

## Issue reference

The issue this PR is linked to: #669 
Will not close this issue, since the issue also asks for ACR and simple app deployment.

## Checklist

Please make sure you've completed the relevant tasks for this PR out of the following list:

* [x] All acceptance criteria in the backlog item are met
* [x] The documentation is updated to cover any new or changed features
* [x] Manual tests have passed
* [x] Relevant issues are linked to this PR

Co-authored-by: @olhakonst17

### CODE REVIEW

**Comment by olhakonst17** [comment]
@mission-lz-reviewers Please let us know if there is any additional details needed on this PR for it to be reviewed. Thanks!

cc: @renato-marciano

**Comment by lisamurphy-msft** [comment]
Thank you for providing this PR @renato-marciano and @olhakonst17 
Unfortunately, this will need to be moved to the 
https://github.com/Azure/missionlz/tree/main/src/bicep/examples folder with an added description in the containing README.md and a subfolder with all the artifacts needed. Are you able to move this to the requested folder?

**Comment by renato-marciano** [comment]
> Thank you for providing this PR @renato-marciano and @olhakonst17 Unfortunately, this will need to be moved to the https://github.com/Azure/missionlz/tree/main/src/bicep/examples folder with an added description in the containing README.md and a subfolder with all the artifacts needed. Are you able to move this to the requested folder?

I have moved the files under examples and have made updates. The Git Action on the Pull Request looks like it's failing because of permission issues.

**Review by lisamurphy-msft — APPROVED** [review]
Thank you for making the requested changes! 
Approving this PR.

**Pull request merged**
