### PR TITLE
Remove default NSG rules for 22 and 3389 from Bicep deployment

### PR DESCRIPTION
**Pull request by vidyambala**
# Description

Removed the default values of Hub NSG rules

## Issue reference

The issue this PR will close: #443 

## Checklist

Please make sure you've completed the relevant tasks for this PR out of the following list:

* [x] All acceptance criteria in the backlog item are met
* [x] The documentation is updated to cover any new or changed features
* [x] Manual tests have passed
* [x] Relevant issues are linked to this PR

### CODE REVIEW

**Review by glennmusa — APPROVED** [review]
Bastion host remote connections over SSH and RDP continue to work after removing these NSG rules with this deployment:

```
my_password=$(openssl rand -base64 14)
az deployment sub create \
  --name "pr538a" \
  --location "eastus" \
  --template-file "src/bicep/mlz.bicep" \
  --parameters deployRemoteAccess="true" \
  --parameters linuxVmAdminPasswordOrKey="$my_password" \
  --parameters windowsVmAdminPassword="$my_password"
```

**Comment by shawngib** [comment]
Not sure I understand the bug since this is most likely not related to our Allow RDP or SSH rule and related to 'AllowVnet' inbound and outbound and bastions in vNet? We should consider enabling JIT on jumpboxes, which is a larger feature add, as it is a compliance requirement in zero trust and other regulations.  @Phydeauxman  would that solve the problem you are trying to solve? 

It does appear it is assigned: I manually deleted allow rdp and ssh in below and tested new branch. I also do not understand priority.
image

**Comment by glennmusa** [comment]
> Not sure I understand the bug since this is most likely not related to our Allow RDP or SSH rule and related to 'AllowVnet' inbound and outbound and bastions in vNet? 

I think the purpose of this specific branch is just to remove these unused rules.

I agree JIT could be a better answer but would require more thought.

**Comment by shawngib** [comment]
If that is the purpose, then done. But it is connected to a bug that will not be changed based on this branch and arguably isn't a bug since 'working as normal' ;)

**Pull request merged**
