### PR TITLE
Updating tools to newer versions

### PR DESCRIPTION
**Pull request by Chambras**
# Description

Just a small maintenance update to upgrade the terraform tools to newer versions.
* Upgrade azurerm provider to 2.90.0
* Upgrade tflint to 0.34.0
* Upgrade tflint azurerm ruleset to 0.14.0

## Issue reference

NA

## Checklist

Please make sure you've completed the relevant tasks for this PR out of the following list:

* [X] All acceptance criteria in the backlog item are met
* [X] The documentation is updated to cover any new or changed features
* [X] Manual tests have passed
* [X] Relevant issues are linked to this PR

### CODE REVIEW

**Review by brooke-hamilton — APPROVED** [review]
@Chambras thank you! ❤️

**Comment by brooke-hamilton** [comment]
@Chambras I'm testing with Azure Cloud Shell on Azure Cloud (Azure commercial). I get the error below, which is the same as issue #528. But that was an issue we were previously seeing only in Azure US Government. Any ideas on this? I'm thinking we would want to merge the PR anyway if it's the same bug, but I want to get your input. (BTW my deployment from the dev container is working as expected.)

```BASH
brooke@Azure:~/missionlz/src/terraform/mlz$ terraform apply
var.hub_subid
  Subscription ID for the Hub deployment

  Enter a value: < my subscription > 

╷
│ Warning: Provider azurerm is undefined
│
│   on main.tf line 221, in module "hub-network":
│  221:   providers  = { azurerm = azurerm.hub }
│
│ Module module.hub-network does not declare a provider named azurerm.
│ If you wish to specify a provider configuration for the module, add an entry for azurerm in the required_providers block within the module.
│
│ (and 11 more similar warnings elsewhere)
╵
╷
│ Error: expected "access_policy.0.object_id" to be a valid UUID, got
│
│   with module.jumpbox[0].azurerm_key_vault.jumpbox-keyvault,
│   on ../modules/jumpbox/main.tf line 18, in resource "azurerm_key_vault" "jumpbox-keyvault":
│   18:     object_id = var.object_id
│
╵
brooke@Azure:~/missionlz/src/terraform/mlz$ terraform version
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.83.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

**Comment by Chambras** [comment]
> @Chambras I'm testing with Azure Cloud Shell on Azure Cloud (Azure commercial). I get the error below, which is the same as issue #528. But that was an issue we were previously seeing only in Azure US Government. Any ideas on this? I'm thinking we would want to merge the PR anyway if it's the same bug, but I want to get your input. (BTW my deployment from the dev container is working as expected.)
> 
> ```shell
> brooke@Azure:~/missionlz/src/terraform/mlz$ terraform apply
> var.hub_subid
>   Subscription ID for the Hub deployment
> 
>   Enter a value: < my subscription > 
> 
> ╷
> │ Warning: Provider azurerm is undefined
> │
> │   on main.tf line 221, in module "hub-network":
> │  221:   providers  = { azurerm = azurerm.hub }
> │
> │ Module module.hub-network does not declare a provider named azurerm.
> │ If you wish to specify a provider configuration for the module, add an entry for azurerm in the required_providers block within the module.
> │
> │ (and 11 more similar warnings elsewhere)
> ╵
> ╷
> │ Error: expected "access_policy.0.object_id" to be a valid UUID, got
> │
> │   with module.jumpbox[0].azurerm_key_vault.jumpbox-keyvault,
> │   on ../modules/jumpbox/main.tf line 18, in resource "azurerm_key_vault" "jumpbox-keyvault":
> │   18:     object_id = var.object_id
> │
> ╵
> brooke@Azure:~/missionlz/src/terraform/mlz$ terraform version
> Terraform v1.0.11
> on linux_amd64
> + provider registry.terraform.io/hashicorp/azurerm v2.83.0
> + provider registry.terraform.io/hashicorp/random v3.1.0
> + provider registry.terraform.io/hashicorp/time v0.7.2
> ```

Hi @brooke-hamilton. Yes, it is the same bug. I did not get that because I use a service principal for all my deployments so if you test in cloud shell using a SP, it should work as well.

**Review by brooke-hamilton — APPROVED** [review]

**Pull request merged**
