### PR TITLE
re-organize scripts to make end-user actions easier to find

### PR DESCRIPTION
**Pull request by glennmusa**
# Description

This change proposes to reorganize the repository to make the end-user scripts and configuration files easier to identify.

### Proposed source organization
With this proposal, `/src/scripts` contains the three scripts we expect end users to invoke and the rest of the implementation is organized under `src/scripts/*`:

```plaintext
└──missionlz
  └──src
    └──scripts
      clean.sh
      deploy.sh
      deploy_ui.sh
      └──config
      └──container-registry
      └──docker
      └──security-center
      └──terraform
      └──util
```

### Proposed name changes
This change also propose these name changes:

| current name | proposed name | what the value represents |
|-|-|-|
| mlz_tf_cfg.var | mlz.config| a file that contains key-value pairs that dictate how MLZ configuration resources are deployed |
| mlz_tf_setup.sh | create_mlz_configuration_resources.sh | a script that deploys MLZ configuration resources by reading the above file |
| setup_ezdeploy.sh | deploy_ui.sh | a script that deploys the MLZ front-end application to Azure Container Registry |
| setup_ezdeploy_local.sh | deploy_ui_local.sh | a script that deploys the MLZ front-end application locally |

## Issue reference

The issue this PR will close: #166

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles or validates correctly
* [x] BASH scripts have been validated using `shellcheck`
* [x] All tests pass (manual and automated)
* [x] The documentation is updated to cover any new or changed features
* [x] Markdown files have been linted using the recommended linter. (See `.vscode/extensions.json`.)
* [x] Relevant issues are linked to this PR

### CODE REVIEW

**Comment by Phydeauxman** [comment]
I am fine with these changes...they make sense. Can we use this as an opportunity to move the scripts that are in `/src` into the `/src/scripts` folder?

**Comment by glennmusa** [comment]
> I am fine with these changes...they make sense. Can we use this as an opportunity to move the scripts that are in `/src` into the `/src/scripts` folder?

Yeah we can do that -- will need to update docs on how to find them

**Review by Breanna-Stryker — APPROVED** [review]
This all looks good to me as well.

**Comment by glennmusa** [comment]
Cool! Thanks everyone. Moving deploy and clean to `src/scripts` so that it's packaged with the air-gapped and UI container, will merge once that is complete. 👍

**Pull request merged**
