### PR TITLE
Update Sentinel Deployment to include Bicep

### PR DESCRIPTION
**Pull request by ExchMaster**
# Description

Updated ./src/bicep/examples/sentinel to include Bicep modules to support the deployment of Sentinel onto an existing deployment of MLZ. 

-sentinel.bicep:  Makes use of a global variable file (MLZDeployment.Outputs).  This has high re-usability simply because it can be referenced by any example that needs outputs from the initial MLZ deployment.
-deploySentinel:   Is the Sentinel module that 'sentinel.bicep' uses to add Sentinel to existing Log Analytics workspace.  This module can be called alone if there is no desire to use the variable file.

This should bring parity between Bicep and the current Terraform deployment for Sentinel

## Issue reference

The issue this PR will close: #405 

## Checklist

Please make sure you've completed the relevant tasks for this PR out of the following list:

* [ x] All acceptance criteria in the backlog item are met
* [ x] The documentation is updated to cover any new or changed features
* [ x] Manual tests have passed
* [ x] Relevant issues are linked to this PR

### CODE REVIEW

**Comment by brooke-hamilton** [comment]
Thank you for submitting a PR, @ExchMaster! 🥇 We will take a detailed look at it. My first impression is that we would want to remove the user/environment-specific settings in `deploymentVariables.json`, but this could still be valuable as a sample for how to configure settings.

**Comment by ExchMaster** [comment]
Thank you @brooke-hamilton, whatever the team thinks is all good.   I deployed a 'Contoso' MLZ specifically so I could show what it would look like using the deploymentVariables.json outputs file specifically so that anyone looking at this would have a full sample.   It's also just really nice to just point every example at one var file and lift everything right out of it.

If we need to make changes, just let me know and I'll jump on it.  Thank you again.

**Comment by ExchMaster** [comment]
Closing PR.   Going to re-submit PR using embedded param within existing Log Analytics workspace module.

**Comment by glennmusa** [comment]
Feel free to keep using this same PR and same branch @ExchMaster -- this PR will be automatically updated with any updates you make and will help the team reviewing the changes to see all the commits.

**Comment by glennmusa** [comment]
Uh oh, looks like the fork is gone entirely and I was just in the middle of a deployment attempt 😄 -- will keep an eye out for your resubmission.

**Pull request closed without merging**
