### PR TITLE
Updated references from docs.microsoft.com - to learn

### PR DESCRIPTION
**Pull request by ElYusubov**
# Description

The PR updates references from docs.microsoft.com - to learn.microsoft

## Issue reference

This PR doesn't close an issue.

## Checklist

Please make sure you've completed the relevant tasks for this PR out of the following list:

* [x] All acceptance criteria in the backlog item are met
* [x] The documentation is updated to cover any new or changed features
* [x] Manual tests have passed
* [x] Relevant issues are linked to this PR

### CODE REVIEW

**Review by kyle-hoyer — APPROVED** [review]
Reviewed links. Approved update from "docs" to "learn"

**Review by mikedzikowski — APPROVED** [review]

**Comment by brooke-hamilton** [comment]
@ElYusubov please merge the latest changes in main into your branch and resolve the conflicts. Thank you for the PR!

**Pull request closed without merging**
